### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by zag2me** [pkscout/metadata.tvshows.thesportsdb.python#2]
Noticed quite a lot of log spam for non matched events. I guess its scanning each event from the JSON for the entire league. Thats going to be quite big for some leagues.

> 2022-05-03 10:33:27.426 T:18240   DEBUG <general>: [metadata.tvshows.thesportsdb.python (1.0.6)]: adding episode information for S2021E369 - English Premier League.20220519.Chelsea vs Leicester to list item
> 2022-05-03 10:33:27.426 T:18240   DEBUG <general>: [metadata.tvshows.thesportsdb.python (1.0.6)]: adding episode information for S2021E370 - English Premier League.20220519.Everton vs Crystal Palace to list item
> 2022-05-03 10:33:27.426 T:18240   DEBUG <general>: [metadata.tvshows.thesportsdb.python (1.0.6)]: adding episode information for S2021E371 - English Premier League.20220522.Leicester vs Southampton to list item
> 2022-05-03 10:33:27.426 T:18240   DEBUG <general>: [metadata.tvshows.thesportsdb.python (1.0.6)]: adding episode information for S2021E372 - English Premier League.20220522.Liverpool vs Wolves to list item
> 2022-05-03 10:33:27.427 T:18240   DEBUG <general>: [metadata.tvshows.thesportsdb.python (1.0.6)]: adding episode information for S2021E373 - English Premier League.20220522.Man City vs Aston Villa to list item
> 2022-05-03 10:33:27.427 T:18240   DEBUG <general>: [metadata.tvshows.thesportsdb.python (1.0.6)]: adding episode information for S2021E374 - English Premier League.20220522.Norwich vs Tottenham to list item
> 2022-05-03 10:33:27.427 T:18240   DEBUG <general>: [metadata.tvshows.thesportsdb.python (1.0.6)]: adding episode information for S2021E375 - English Premier League.20220522.Arsenal vs Everton to list item
> 2022-05-03 10:33:27.427 T:18240   DEBUG <general>: [metadata.tvshows.thesportsdb.python (1.0.6)]: adding episode information for S2021E376 - English Premier League.20220522.Brentford vs Leeds to list item
> 2022-05-03 10:33:27.427 T:18240   DEBUG <general>: [metadata.tvshows.thesportsdb.python (1.0.6)]: adding episode information for S2021E377 - English Premier League.20220522.Brighton vs West Ham to list item
> 2022-05-03 10:33:27.427 T:18240   DEBUG <general>: [metadata.tvshows.thesportsdb.python (1.0.6)]: adding episode information for S2021E378 - English Premier League.20220522.Burnley vs Newcastle to list item
> 2022-05-03 10:33:27.427 T:18240   DEBUG <general>: [metadata.tvshows.thesportsdb.python (1.0.6)]: adding episode information for S2021E379 - English Premier League.20220522.Chelsea vs Watford to list item
> 2022-05-03 10:33:27.427 T:18240   DEBUG <general>: [metadata.tvshows.thesportsdb.python (1.0.6)]: adding episode information for S2021E380 - English Premier League.20220522.Crystal Palace vs Man United to list item

[kodi.log](https://github.com/pkscout/metadata.tvshows.thesportsdb.python/files/8609627/kodi.log)

**Comment by pkscout** [comment]
The way the Python scraper works, you have to load all the episodes for a show into a list item during one step (getepisodelist) so that core can use that list to match against when it calls getepisodedetail.  So yes, it can get quite long, but none of the sports stuff is as bad as something like The Simpsons or other really long running series.  I log all that (and a bunch of other stuff) in debug mode for troubleshooting if someone is having issues.  Regular users running at the normal log level will see almost nothing in the logs.
