### ISSUE TITLE
Kodi Forum Link

### ISSUE THREAD

**Issue by pkscout** [pkscout/metadata.tvshows.thesportsdb.python#3]
@zag2me, do you want to have a different forum post for the Python scraper?  Right now the forum link in `addon.xml` is to the one you just opened for the XML scraper.  I don't think it matters much either way, I just want to have the right forum link in the add on information when it does get into the official repo.

**Comment by zag2me** [comment]
Yes please, new forum post. Lets keep things seperate.

**Comment by zag2me** [comment]
Are you going to make a new thread on the Kodi forums for this?

Would be good to get some other users testing.

A few users have tested on the TSDB discord channel and been sucessful.

**Comment by pkscout** [comment]
I did start a new thread. 

https://forum.kodi.tv/showthread.php?tid=368208

I already submitted to the scraper repo, but the PR hasn't been reviewed. I can pull it and update the forum thread with a link to my GitHub repo for testing if you'd like.

**Comment by zag2me** [comment]
Great, I'll post in the thread. Feel free to close this issue.
